const express = require('express');
const session = require('express-session');
const bcrypt = require('bcryptjs');
const crypto = require('crypto');
const path = require('path');

const PORT = process.env.PORT || 3000;
const isPg = Boolean(process.env.DATABASE_URL);
const app = express();
let sessionMiddleware = null;

app.set('trust proxy', 1);
app.use(express.json({limit:'4mb'}));
app.use(express.urlencoded({extended:true}));
app.use((req,res,next)=>sessionMiddleware ? sessionMiddleware(req,res,next) : next());

let db, pool;

const PG_SCHEMA = `
CREATE TABLE IF NOT EXISTS users(id SERIAL PRIMARY KEY,email TEXT UNIQUE NOT NULL,password TEXT NOT NULL,name TEXT NOT NULL,created_at TIMESTAMPTZ DEFAULT NOW());
CREATE TABLE IF NOT EXISTS teams(id SERIAL PRIMARY KEY,name TEXT NOT NULL,description TEXT DEFAULT '',period TEXT DEFAULT '',created_by INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,created_at TIMESTAMPTZ DEFAULT NOW());
CREATE TABLE IF NOT EXISTS memberships(id SERIAL PRIMARY KEY,team_id INTEGER NOT NULL REFERENCES teams(id) ON DELETE CASCADE,user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,role TEXT NOT NULL CHECK(role IN('leader','member')),position TEXT DEFAULT 'Member',UNIQUE(team_id,user_id));
CREATE TABLE IF NOT EXISTS invites(id SERIAL PRIMARY KEY,team_id INTEGER NOT NULL REFERENCES teams(id) ON DELETE CASCADE,email TEXT NOT NULL,role TEXT DEFAULT 'member',position TEXT DEFAULT 'Member',token TEXT UNIQUE NOT NULL,status TEXT DEFAULT 'pending',created_at TIMESTAMPTZ DEFAULT NOW());
CREATE TABLE IF NOT EXISTS tasks(id SERIAL PRIMARY KEY,team_id INTEGER NOT NULL REFERENCES teams(id) ON DELETE CASCADE,title TEXT NOT NULL,description TEXT DEFAULT '',assignee_id INTEGER REFERENCES users(id) ON DELETE SET NULL,creator_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,start_date TEXT,deadline TEXT,priority TEXT DEFAULT 'Medium',effort INTEGER DEFAULT 3,status TEXT DEFAULT 'todo',progress INTEGER DEFAULT 0,actual_effort REAL,evidence_link TEXT,evidence_note TEXT,submitted_at TIMESTAMPTZ,reviewed_at TIMESTAMPTZ,reviewer_id INTEGER REFERENCES users(id) ON DELETE SET NULL,review_status TEXT,review_feedback TEXT,created_at TIMESTAMPTZ DEFAULT NOW());
CREATE TABLE IF NOT EXISTS task_history(id SERIAL PRIMARY KEY,task_id INTEGER NOT NULL REFERENCES tasks(id) ON DELETE CASCADE,user_id INTEGER REFERENCES users(id) ON DELETE SET NULL,action TEXT NOT NULL,detail TEXT DEFAULT '',created_at TIMESTAMPTZ DEFAULT NOW());
CREATE TABLE IF NOT EXISTS calendar_events(id SERIAL PRIMARY KEY,user_id INTEGER REFERENCES users(id) ON DELETE CASCADE,team_id INTEGER REFERENCES teams(id) ON DELETE CASCADE,type TEXT NOT NULL,title TEXT NOT NULL,date TEXT NOT NULL,time TEXT DEFAULT '',description TEXT DEFAULT '',meeting_link TEXT DEFAULT '',task_id INTEGER REFERENCES tasks(id) ON DELETE CASCADE,created_at TIMESTAMPTZ DEFAULT NOW());
CREATE TABLE IF NOT EXISTS peer_reviews(id SERIAL PRIMARY KEY,team_id INTEGER NOT NULL REFERENCES teams(id) ON DELETE CASCADE,reviewer_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,reviewee_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,responsibility INTEGER,punctuality INTEGER,quality INTEGER,collaboration INTEGER,feedback TEXT DEFAULT '',created_at TIMESTAMPTZ DEFAULT NOW(),UNIQUE(team_id,reviewer_id,reviewee_id));
CREATE TABLE IF NOT EXISTS settings(user_id INTEGER PRIMARY KEY REFERENCES users(id) ON DELETE CASCADE,language TEXT DEFAULT 'en',theme TEXT DEFAULT 'light',week_start TEXT DEFAULT 'monday');
CREATE TABLE IF NOT EXISTS app_state(user_id INTEGER PRIMARY KEY REFERENCES users(id) ON DELETE CASCADE,state TEXT NOT NULL,updated_at TIMESTAMPTZ DEFAULT NOW());
`;
const SQLITE_SCHEMA = `
PRAGMA foreign_keys=ON;
CREATE TABLE IF NOT EXISTS users(id INTEGER PRIMARY KEY AUTOINCREMENT,email TEXT UNIQUE NOT NULL,password TEXT NOT NULL,name TEXT NOT NULL,created_at TEXT DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS teams(id INTEGER PRIMARY KEY AUTOINCREMENT,name TEXT NOT NULL,description TEXT DEFAULT '',period TEXT DEFAULT '',created_by INTEGER NOT NULL,created_at TEXT DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS memberships(id INTEGER PRIMARY KEY AUTOINCREMENT,team_id INTEGER NOT NULL,user_id INTEGER NOT NULL,role TEXT NOT NULL CHECK(role IN('leader','member')),position TEXT DEFAULT 'Member',UNIQUE(team_id,user_id));
CREATE TABLE IF NOT EXISTS invites(id INTEGER PRIMARY KEY AUTOINCREMENT,team_id INTEGER NOT NULL,email TEXT NOT NULL,role TEXT DEFAULT 'member',position TEXT DEFAULT 'Member',token TEXT UNIQUE NOT NULL,status TEXT DEFAULT 'pending',created_at TEXT DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS tasks(id INTEGER PRIMARY KEY AUTOINCREMENT,team_id INTEGER NOT NULL,title TEXT NOT NULL,description TEXT DEFAULT '',assignee_id INTEGER,creator_id INTEGER NOT NULL,start_date TEXT,deadline TEXT,priority TEXT DEFAULT 'Medium',effort INTEGER DEFAULT 3,status TEXT DEFAULT 'todo',progress INTEGER DEFAULT 0,actual_effort REAL,evidence_link TEXT,evidence_note TEXT,submitted_at TEXT,reviewed_at TEXT,reviewer_id INTEGER,review_status TEXT,review_feedback TEXT,created_at TEXT DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS task_history(id INTEGER PRIMARY KEY AUTOINCREMENT,task_id INTEGER NOT NULL,user_id INTEGER,action TEXT NOT NULL,detail TEXT DEFAULT '',created_at TEXT DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS calendar_events(id INTEGER PRIMARY KEY AUTOINCREMENT,user_id INTEGER,team_id INTEGER,type TEXT NOT NULL,title TEXT NOT NULL,date TEXT NOT NULL,time TEXT DEFAULT '',description TEXT DEFAULT '',meeting_link TEXT DEFAULT '',task_id INTEGER,created_at TEXT DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS peer_reviews(id INTEGER PRIMARY KEY AUTOINCREMENT,team_id INTEGER NOT NULL,reviewer_id INTEGER NOT NULL,reviewee_id INTEGER NOT NULL,responsibility INTEGER,punctuality INTEGER,quality INTEGER,collaboration INTEGER,feedback TEXT DEFAULT '',created_at TEXT DEFAULT CURRENT_TIMESTAMP,UNIQUE(team_id,reviewer_id,reviewee_id));
CREATE TABLE IF NOT EXISTS settings(user_id INTEGER PRIMARY KEY,language TEXT DEFAULT 'en',theme TEXT DEFAULT 'light',week_start TEXT DEFAULT 'monday');
CREATE TABLE IF NOT EXISTS app_state(user_id INTEGER PRIMARY KEY, state TEXT NOT NULL, updated_at TEXT DEFAULT CURRENT_TIMESTAMP);
`;

function qmarks(sql){let i=0;return sql.replace(/\?/g,()=>`$${++i}`)}
async function all(sql,params=[]){if(isPg){const r=await pool.query(qmarks(sql),params);return r.rows;}return db.prepare(sql).all(params)}
async function one(sql,params=[]){if(isPg){const r=await pool.query(qmarks(sql),params);return r.rows[0]||null;}return db.prepare(sql).get(params)}
async function exec(sql,params=[]){
  if(isPg){const r=await pool.query(qmarks(sql),params);return {changes:r.rowCount,lastInsertId:r.rows[0]?.id};}
  const stmt=db.prepare(sql);
  if(/\bRETURNING\b/i.test(sql)){
    const row=stmt.get(params);
    return {changes:row?1:0,lastInsertId:row?.id ?? null,row};
  }
  const r=stmt.run(params);
  return {changes:r.changes,lastInsertId:r.lastInsertRowid};
}
async function initDb(){
  if(isPg){const {Pool}=require('pg');pool=new Pool({connectionString:process.env.DATABASE_URL,ssl:process.env.DATABASE_URL.includes('sslmode=require')||process.env.NODE_ENV==='production'?{rejectUnauthorized:false}:false,max:5});await pool.query(PG_SCHEMA);}
  else {const Database=require('better-sqlite3');const fs=require('fs');fs.mkdirSync(path.join(__dirname,'database'),{recursive:true});db=new Database(path.join(__dirname,'database','fairteam.db'));db.pragma('foreign_keys = ON');db.exec(SQLITE_SCHEMA);}
}

function cleanUser(u){return u?{id:u.id,email:u.email,name:u.name}:null}
async function auth(req,res,next){if(!req.session.userId)return res.status(401).json({error:'Please log in'});next()}
async function membership(userId,teamId){return one('SELECT * FROM memberships WHERE team_id=? AND user_id=?',[teamId,userId])}
async function requireMember(req,res,teamId){const m=await membership(req.session.userId,teamId);if(!m){res.status(403).json({error:'Access denied'});return null}return m}
async function requireLeader(req,res,teamId){const m=await requireMember(req,res,teamId);if(m&&m.role!=='leader'){res.status(403).json({error:'Leader only'});return null}return m}
function token(){return crypto.randomBytes(20).toString('hex')}

app.post('/api/auth/signup',async(req,res,next)=>{try{const {name,email,password}=req.body||{};const e=String(email||'').trim().toLowerCase();if(!name||!e||!password||password.length<6)return res.status(400).json({error:'Name, email and password (6+ chars) are required'});if(await one('SELECT id FROM users WHERE email=?',[e]))return res.status(409).json({error:'Email already registered'});const hash=await bcrypt.hash(password,10);const r=await exec('INSERT INTO users(name,email,password) VALUES(?,?,?) RETURNING id',[name.trim(),e,hash]);const uid=r.lastInsertId;await exec('INSERT INTO settings(user_id) VALUES(?)',[uid]);req.session.userId=uid;res.json({user:cleanUser(await one('SELECT * FROM users WHERE id=?',[uid]))});}catch(e){next(e)}});
app.post('/api/auth/login',async(req,res,next)=>{try{const u=await one('SELECT * FROM users WHERE email=?',[String(req.body.email||'').trim().toLowerCase()]);if(!u||!(await bcrypt.compare(req.body.password||'',u.password)))return res.status(401).json({error:'Invalid email or password'});req.session.userId=u.id;res.json({user:cleanUser(u)});}catch(e){next(e)}});
// Google OAuth 2.0. Set GOOGLE_CLIENT_ID and GOOGLE_CLIENT_SECRET to enable it.
app.get('/api/auth/google',(req,res)=>{
  const id=process.env.GOOGLE_CLIENT_ID;
  if(!id||!process.env.GOOGLE_CLIENT_SECRET)return res.status(503).send('Google Sign-In is not configured yet.');
  const redirect=`${req.protocol}://${req.get('host')}/api/auth/google/callback`;
  const u=new URL('https://accounts.google.com/o/oauth2/v2/auth');
  u.searchParams.set('client_id',id);u.searchParams.set('redirect_uri',redirect);u.searchParams.set('response_type','code');
  u.searchParams.set('scope','openid email profile');u.searchParams.set('access_type','online');u.searchParams.set('prompt','select_account');
  res.redirect(u.toString());
});
app.get('/api/auth/google/callback',async(req,res,next)=>{try{
  if(!process.env.GOOGLE_CLIENT_ID||!process.env.GOOGLE_CLIENT_SECRET)return res.status(503).send('Google Sign-In is not configured yet.');
  const code=String(req.query.code||'');if(!code)return res.redirect('/?google=cancelled');
  const redirect=`${req.protocol}://${req.get('host')}/api/auth/google/callback`;
  const tr=await fetch('https://oauth2.googleapis.com/token',{method:'POST',headers:{'Content-Type':'application/x-www-form-urlencoded'},body:new URLSearchParams({code,client_id:process.env.GOOGLE_CLIENT_ID,client_secret:process.env.GOOGLE_CLIENT_SECRET,redirect_uri:redirect,grant_type:'authorization_code'})});
  const tok=await tr.json();if(!tr.ok||!tok.access_token)throw new Error(tok.error_description||'Google token exchange failed');
  const ir=await fetch('https://www.googleapis.com/oauth2/v3/userinfo',{headers:{Authorization:`Bearer ${tok.access_token}`}});const info=await ir.json();
  const email=String(info.email||'').trim().toLowerCase();const name=String(info.name||info.given_name||'Google User').trim();
  if(!email||info.email_verified===false)throw new Error('Google account email is not verified');
  let u=await one('SELECT * FROM users WHERE email=?',[email]);
  if(!u){const hash=await bcrypt.hash(crypto.randomBytes(32).toString('hex'),10);const r=await exec('INSERT INTO users(name,email,password) VALUES(?,?,?) RETURNING id',[name,email,hash]);await exec('INSERT INTO settings(user_id) VALUES(?)',[r.lastInsertId]);u=await one('SELECT * FROM users WHERE id=?',[r.lastInsertId]);}
  req.session.userId=u.id;res.redirect('/');
}catch(e){next(e)}});

app.post('/api/auth/logout',(req,res)=>req.session.destroy(()=>res.json({ok:true})));
app.get('/api/me',auth,async(req,res,next)=>{try{const user=await one('SELECT * FROM users WHERE id=?',[req.session.userId]);const settings=await one('SELECT * FROM settings WHERE user_id=?',[req.session.userId]);res.json({user:cleanUser(user),settings});}catch(e){next(e)}});
app.patch('/api/settings',auth,async(req,res,next)=>{try{const b=req.body||{};await exec('INSERT INTO settings(user_id,language,theme,week_start) VALUES(?,?,?,?) ON CONFLICT(user_id) DO UPDATE SET language=COALESCE(?,settings.language),theme=COALESCE(?,settings.theme),week_start=COALESCE(?,settings.week_start)',[req.session.userId,b.language||'en',b.theme||'light',b.week_start||'monday',b.language||null,b.theme||null,b.week_start||null]);res.json(await one('SELECT * FROM settings WHERE user_id=?',[req.session.userId]));}catch(e){next(e)}});

app.get('/api/teams',auth,async(req,res,next)=>{try{res.json(await all(`SELECT t.*,m.role,m.position,(SELECT COUNT(*) FROM memberships x WHERE x.team_id=t.id) members,(SELECT COUNT(*) FROM tasks x WHERE x.team_id=t.id) tasks,(SELECT COUNT(*) FROM tasks x WHERE x.team_id=t.id AND x.status='verified') verified FROM teams t JOIN memberships m ON m.team_id=t.id AND m.user_id=? ORDER BY t.id DESC`,[req.session.userId]));}catch(e){next(e)}});
app.post('/api/teams',auth,async(req,res,next)=>{try{const b=req.body||{};if(!b.name?.trim())return res.status(400).json({error:'Team name is required'});const r=await exec('INSERT INTO teams(name,description,period,created_by) VALUES(?,?,?,?) RETURNING id',[b.name.trim(),b.description||'',b.period||'',req.session.userId]);await exec('INSERT INTO memberships(team_id,user_id,role,position) VALUES(?,?,?,?)',[r.lastInsertId,req.session.userId,'leader',b.position||'Project Lead']);res.json({id:r.lastInsertId});}catch(e){next(e)}});
app.get('/api/teams/:id',auth,async(req,res,next)=>{try{const m=await requireMember(req,res,req.params.id);if(!m)return;const t=await one('SELECT * FROM teams WHERE id=?',[req.params.id]);const members=await all(`SELECT m.*,u.name,u.email FROM memberships m JOIN users u ON u.id=m.user_id WHERE m.team_id=? ORDER BY CASE WHEN m.role='leader' THEN 0 ELSE 1 END,u.name`,[req.params.id]);const tasks=await all(`SELECT t.*,u.name assignee_name,c.name creator_name FROM tasks t LEFT JOIN users u ON u.id=t.assignee_id LEFT JOIN users c ON c.id=t.creator_id WHERE t.team_id=? ORDER BY t.deadline NULLS LAST,t.id DESC`,[req.params.id]);const invites=await all('SELECT id,email,role,position,status,created_at FROM invites WHERE team_id=? AND status=\'pending\' ORDER BY id DESC',[req.params.id]);res.json({team:t,membership:m,members,tasks,invites});}catch(e){next(e)}});
app.delete('/api/teams/:id',auth,async(req,res,next)=>{try{const m=await requireLeader(req,res,req.params.id);if(!m)return;const team=await one('SELECT id FROM teams WHERE id=?',[req.params.id]);if(!team)return res.status(404).json({error:'Team not found'});const total=await one('SELECT COUNT(*) count FROM tasks WHERE team_id=?',[req.params.id]);const verified=await one("SELECT COUNT(*) count FROM tasks WHERE team_id=? AND status='verified'",[req.params.id]);if(Number(total.count)<=0||Number(total.count)!==Number(verified.count))return res.status(400).json({error:'A team can only be deleted after all tasks are verified'});await exec('DELETE FROM teams WHERE id=?',[req.params.id]);res.json({ok:true});}catch(e){next(e)}});
app.post('/api/teams/:id/invites',auth,async(req,res,next)=>{try{if(!await requireLeader(req,res,req.params.id))return;const tok=token();const position=String(req.body.position||'Member').trim()||'Member';await exec('INSERT INTO invites(team_id,email,position,token) VALUES(?,?,?,?)',[req.params.id,'',position,tok]);res.json({token:tok,inviteLink:`${req.protocol}://${req.get('host')}/?invite=${tok}`});}catch(e){next(e)}});
app.get('/api/invites/:token',async(req,res,next)=>{try{const i=await one(`SELECT i.id,i.team_id,i.position,i.token,i.status,i.created_at,t.name team_name,u.name inviter FROM invites i JOIN teams t ON t.id=i.team_id JOIN users u ON u.id=t.created_by WHERE i.token=?`,[req.params.token]);if(!i)return res.status(404).json({error:'Invite not found'});res.json(i);}catch(e){next(e)}});
app.post('/api/invites/:token/accept',auth,async(req,res,next)=>{try{const i=await one('SELECT * FROM invites WHERE token=?',[req.params.token]);if(!i||i.status!=='pending')return res.status(400).json({error:'Invite unavailable'});await exec('INSERT INTO memberships(team_id,user_id,role,position) VALUES(?,?,?,?) ON CONFLICT(team_id,user_id) DO NOTHING',[i.team_id,req.session.userId,'member',i.position]);await exec("UPDATE invites SET status='active' WHERE id=?",[i.id]);res.json({ok:true,teamId:i.team_id});}catch(e){next(e)}});
app.post('/api/sample-team',auth,async(req,res,next)=>{try{
  const existing=await one("SELECT id FROM teams WHERE created_by=? AND name=?",[req.session.userId,'FairTeam Sample Project']);if(existing)return res.json({id:existing.id,existing:true});
  const r=await exec('INSERT INTO teams(name,description,period,created_by) VALUES(?,?,?,?) RETURNING id',['FairTeam Sample Project','Sample workspace with five members to explore the full workflow.','Sample evaluation period',req.session.userId]);const tid=r.lastInsertId;
  await exec('INSERT INTO memberships(team_id,user_id,role,position) VALUES(?,?,?,?)',[tid,req.session.userId,'leader','Project Lead']);
  const sample=[['Minh','Data Analyst'],['Linh','Researcher'],['An','Content Lead'],['Khoa','Designer']];const ids=[];
  for(const [name,pos] of sample){const email=`${name.toLowerCase()}@sample.fairteam.local`;let u=await one('SELECT * FROM users WHERE email=?',[email]);if(!u){const hash=await bcrypt.hash('sample123',10);const ur=await exec('INSERT INTO users(name,email,password) VALUES(?,?,?) RETURNING id',[name,email,hash]);await exec('INSERT INTO settings(user_id) VALUES(?)',[ur.lastInsertId]);u=await one('SELECT * FROM users WHERE id=?',[ur.lastInsertId]);}ids.push(u.id);await exec('INSERT INTO memberships(team_id,user_id,role,position) VALUES(?,?,?,?) ON CONFLICT(team_id,user_id) DO NOTHING',[tid,u.id,'member',pos]);}
  const taskData=[['Research market references',ids[1],35,'verified'],['Clean survey data',ids[0],60,'in_progress'],['Draft project outline',ids[2],45,'todo'],['Create presentation direction',ids[3],70,'in_progress'],['Prepare team meeting notes',req.session.userId,20,'todo']];
  for(const [title,assignee,progress,status] of taskData){await exec('INSERT INTO tasks(team_id,title,description,assignee_id,creator_id,priority,effort,status,progress) VALUES(?,?,?,?,?,?,?,?,?) RETURNING id',[tid,title,'Sample task for testing the FairTeam workflow.',assignee,req.session.userId,'Medium',3,status,progress]);}
  res.json({id:tid,created:true});
}catch(e){next(e)}});

app.get('/api/tasks',auth,async(req,res,next)=>{try{res.json(await all(`SELECT t.*,tm.name team_name,u.name assignee_name FROM tasks t JOIN teams tm ON tm.id=t.team_id LEFT JOIN users u ON u.id=t.assignee_id JOIN memberships m ON m.team_id=t.team_id AND m.user_id=? ORDER BY CASE WHEN t.deadline IS NULL THEN 1 ELSE 0 END,t.deadline,t.id DESC`,[req.session.userId]));}catch(e){next(e)}});
app.post('/api/teams/:teamId/tasks',auth,async(req,res,next)=>{try{if(!await requireMember(req,res,req.params.teamId))return;const b=req.body||{};if(!b.title?.trim())return res.status(400).json({error:'Task title required'});const assignee=Number(b.assignee_id)||req.session.userId;const effort=Math.min(5,Math.max(1,Number(b.effort)||3));const r=await exec(`INSERT INTO tasks(team_id,title,description,assignee_id,creator_id,start_date,deadline,priority,effort) VALUES(?,?,?,?,?,?,?,?,?) RETURNING id`,[req.params.teamId,b.title.trim(),b.description||'',assignee,req.session.userId,b.start_date||null,b.deadline||null,b.priority||'Medium',effort]);await exec('INSERT INTO task_history(task_id,user_id,action,detail) VALUES(?,?,?,?)',[r.lastInsertId,req.session.userId,'assigned','Task created']);if(b.deadline)await exec('INSERT INTO calendar_events(user_id,team_id,type,title,date,description,task_id) VALUES(?,?,?,?,?,?,?)',[assignee,req.params.teamId,'task',b.title.trim(),b.deadline,b.description||'',r.lastInsertId]);res.json({id:r.lastInsertId});}catch(e){next(e)}});
app.get('/api/tasks/:id',auth,async(req,res,next)=>{try{const t=await one(`SELECT t.*,tm.name team_name,a.name assignee_name,c.name creator_name FROM tasks t JOIN teams tm ON tm.id=t.team_id LEFT JOIN users a ON a.id=t.assignee_id LEFT JOIN users c ON c.id=t.creator_id WHERE t.id=?`,[req.params.id]);if(!t||!await membership(req.session.userId,t.team_id))return res.status(403).json({error:'Access denied'});const history=await all(`SELECT h.*,u.name FROM task_history h LEFT JOIN users u ON u.id=h.user_id WHERE h.task_id=? ORDER BY h.id DESC`,[req.params.id]);res.json({task:t,history});}catch(e){next(e)}});
app.patch('/api/tasks/:id',auth,async(req,res,next)=>{try{const t=await one('SELECT * FROM tasks WHERE id=?',[req.params.id]);if(!t||!await membership(req.session.userId,t.team_id))return res.status(403).json({error:'Access denied'});const b=req.body||{};await exec(`UPDATE tasks SET title=COALESCE(?,title),description=COALESCE(?,description),deadline=COALESCE(?,deadline),priority=COALESCE(?,priority),effort=COALESCE(?,effort),progress=COALESCE(?,progress),status=COALESCE(?,status) WHERE id=?`,[b.title||null,b.description??null,b.deadline??null,b.priority||null,b.effort||null,b.progress??null,b.status||null,t.id]);if(b.deadline&&b.deadline!==t.deadline)await exec('UPDATE calendar_events SET date=? WHERE task_id=?',[b.deadline,t.id]);await exec('INSERT INTO task_history(task_id,user_id,action,detail) VALUES(?,?,?,?)',[t.id,req.session.userId,'updated','Task updated']);res.json({ok:true});}catch(e){next(e)}});
app.delete('/api/tasks/:id',auth,async(req,res,next)=>{try{const t=await one('SELECT * FROM tasks WHERE id=?',[req.params.id]);if(!t||!await membership(req.session.userId,t.team_id))return res.status(403).json({error:'Access denied'});if(t.status!=='verified')return res.status(400).json({error:'Only verified tasks can be deleted'});await exec('DELETE FROM tasks WHERE id=?',[t.id]);res.json({ok:true});}catch(e){next(e)}});
app.post('/api/tasks/:id/effort',auth,async(req,res,next)=>{try{const t=await one('SELECT * FROM tasks WHERE id=?',[req.params.id]);if(!t||!await membership(req.session.userId,t.team_id))return res.status(403).json({error:'Access denied'});const effort=Math.min(5,Math.max(1,Number(req.body.effort)||t.effort));const note=String(req.body.note||'').trim();await exec('UPDATE tasks SET effort=? WHERE id=?',[effort,t.id]);await exec('INSERT INTO task_history(task_id,user_id,action,detail) VALUES(?,?,?,?)',[t.id,req.session.userId,'effort_updated',note||`Effort set to ${effort}`]);res.json({ok:true});}catch(e){next(e)}});
app.post('/api/tasks/:id/submit',auth,async(req,res,next)=>{try{const t=await one('SELECT * FROM tasks WHERE id=?',[req.params.id]);if(!t||t.assignee_id!==req.session.userId)return res.status(403).json({error:'Only the assignee can submit this task'});if(!['todo','in_progress','changes_requested'].includes(t.status))return res.status(400).json({error:'Task cannot be submitted in its current status'});const b=req.body||{};if(!b.evidence_link&&!b.evidence_note)return res.status(400).json({error:'Please provide evidence or a completion note'});await exec(`UPDATE tasks SET status='pending_review',progress=100,evidence_link=?,evidence_note=?,actual_effort=?,submitted_at=CURRENT_TIMESTAMP,review_status='pending',review_feedback=NULL WHERE id=?`,[b.evidence_link||'',b.evidence_note||'',b.actual_effort||null,t.id]);await exec('INSERT INTO task_history(task_id,user_id,action,detail) VALUES(?,?,?,?)',[t.id,req.session.userId,'evidence_submitted','Evidence submitted for leader review']);res.json({ok:true});}catch(e){next(e)}});
app.post('/api/tasks/:id/review',auth,async(req,res,next)=>{try{const t=await one('SELECT * FROM tasks WHERE id=?',[req.params.id]);if(!t)return res.status(404).json({error:'Task not found'});if(!await requireLeader(req,res,t.team_id))return;if(t.assignee_id===req.session.userId)return res.status(400).json({error:'A leader cannot verify their own task'});const b=req.body||{};if(!['verify','changes'].includes(b.action)||!String(b.feedback||'').trim())return res.status(400).json({error:'Choose a review result and provide feedback'});const status=b.action==='verify'?'verified':'changes_requested';await exec(`UPDATE tasks SET status=?,review_status=?,review_feedback=?,reviewed_at=CURRENT_TIMESTAMP,reviewer_id=? WHERE id=?`,[status,b.action,String(b.feedback).trim(),req.session.userId,t.id]);await exec('INSERT INTO task_history(task_id,user_id,action,detail) VALUES(?,?,?,?)',[t.id,req.session.userId,b.action==='verify'?'verified':'changes_requested',String(b.feedback).trim()]);res.json({ok:true});}catch(e){next(e)}});

app.get('/api/reviews/queue',auth,async(req,res,next)=>{try{const rows=await all(`SELECT t.*,tm.name team_name,u.name assignee_name FROM tasks t JOIN teams tm ON tm.id=t.team_id JOIN users u ON u.id=t.assignee_id JOIN memberships m ON m.team_id=t.team_id AND m.user_id=? AND m.role='leader' WHERE t.status='pending_review' AND t.assignee_id<>? ORDER BY t.submitted_at`,[req.session.userId,req.session.userId]);res.json(rows);}catch(e){next(e)}});
app.get('/api/reviews/recent',auth,async(req,res,next)=>{try{res.json(await all(`SELECT t.id,t.title,t.status,t.review_feedback,t.reviewed_at,tm.name team_name,u.name reviewer_name FROM tasks t JOIN teams tm ON tm.id=t.team_id LEFT JOIN users u ON u.id=t.reviewer_id WHERE t.assignee_id=? AND t.status IN('verified','changes_requested') ORDER BY t.reviewed_at DESC LIMIT 6`,[req.session.userId]));}catch(e){next(e)}});

app.get('/api/calendar',auth,async(req,res,next)=>{try{res.json(await all(`SELECT e.*,tm.name team_name FROM calendar_events e LEFT JOIN teams tm ON tm.id=e.team_id WHERE e.user_id=? OR (e.team_id IN (SELECT team_id FROM memberships WHERE user_id=?) AND e.type<>'personal') ORDER BY e.date,e.time,e.id`,[req.session.userId,req.session.userId]));}catch(e){next(e)}});
app.post('/api/calendar',auth,async(req,res,next)=>{try{const b=req.body||{};if(!b.title||!b.date)return res.status(400).json({error:'Title and date are required'});await exec('INSERT INTO calendar_events(user_id,team_id,type,title,date,time,description,meeting_link,task_id) VALUES(?,?,?,?,?,?,?,?,?)',[req.session.userId,b.team_id||null,b.type||'note',b.title,b.date,b.time||'',b.description||'',b.meeting_link||'',b.task_id||null]);res.json({ok:true});}catch(e){next(e)}});
app.delete('/api/calendar/:id',auth,async(req,res,next)=>{try{const e=await one('SELECT * FROM calendar_events WHERE id=?',[req.params.id]);if(!e)return res.status(404).json({error:'Event not found'});const m=e.team_id?await membership(req.session.userId,e.team_id):null;if(e.user_id!==req.session.userId&&m?.role!=='leader')return res.status(403).json({error:'Not allowed'});await exec('DELETE FROM calendar_events WHERE id=?',[req.params.id]);res.json({ok:true});}catch(e){next(e)}});

app.get('/api/teams/:id/reviews',auth,async(req,res,next)=>{try{if(!await requireMember(req,res,req.params.id))return;const rows=await all(`SELECT r.*,u.name reviewee_name FROM peer_reviews r JOIN users u ON u.id=r.reviewee_id WHERE r.team_id=? AND r.reviewer_id=?`,[req.params.id,req.session.userId]);res.json(rows);}catch(e){next(e)}});
app.post('/api/teams/:id/reviews',auth,async(req,res,next)=>{try{if(!await requireMember(req,res,req.params.id))return;const b=req.body||{};const vals=['responsibility','punctuality','quality','collaboration'].map(k=>Math.min(5,Math.max(1,Number(b[k])||1)));if(Number(b.reviewee_id)===req.session.userId)return res.status(400).json({error:'You cannot review yourself'});await exec(`INSERT INTO peer_reviews(team_id,reviewer_id,reviewee_id,responsibility,punctuality,quality,collaboration,feedback) VALUES(?,?,?,?,?,?,?,?) ON CONFLICT(team_id,reviewer_id,reviewee_id) DO UPDATE SET responsibility=?,punctuality=?,quality=?,collaboration=?,feedback=?`,[req.params.id,req.session.userId,b.reviewee_id,...vals,b.feedback||'',...vals,b.feedback||'']);res.json({ok:true});}catch(e){next(e)}});

app.get('/api/teams/:id/contribution',auth,async(req,res,next)=>{try{if(!await requireMember(req,res,req.params.id))return;const members=await all(`SELECT m.user_id,u.name,m.role,m.position FROM memberships m JOIN users u ON u.id=m.user_id WHERE m.team_id=?`,[req.params.id]);const result=[];for(const m of members){const total=await one('SELECT COUNT(*) count FROM tasks WHERE team_id=? AND assignee_id=?',[req.params.id,m.user_id]);const verified=await one(`SELECT COUNT(*) count FROM tasks WHERE team_id=? AND assignee_id=? AND status='verified'`,[req.params.id,m.user_id]);const quality=await one(`SELECT AVG(CASE WHEN status='verified' THEN 5.0 ELSE CASE WHEN review_status='changes' THEN 3.0 ELSE 4.0 END END) score FROM tasks WHERE team_id=? AND assignee_id=?`,[req.params.id,m.user_id]);const ontime=await one(`SELECT AVG(CASE WHEN status='verified' AND (deadline IS NULL OR submitted_at IS NULL OR submitted_at<=deadline) THEN 100.0 WHEN status='verified' THEN 85.0 ELSE 60.0 END) score FROM tasks WHERE team_id=? AND assignee_id=?`,[req.params.id,m.user_id]);const peer=await one(`SELECT AVG((responsibility+punctuality+quality+collaboration)/4.0) score FROM peer_reviews WHERE team_id=? AND reviewee_id=?`,[req.params.id,m.user_id]);const taskScore=Number(total.count)?Math.min(100,Number(verified.count)/Number(total.count)*100):0;const workQuality=Number(quality.score||0)/5*100;const reliability=Number(ontime.score||0);const peerScore=Number(peer.score||0)/5*100;const score=taskScore*.3+workQuality*.3+reliability*.2+peerScore*.2;result.push({user_id:m.user_id,name:m.name,role:m.role,position:m.position,total:Number(total.count),verified:Number(verified.count),taskContribution:Math.round(taskScore),workQuality:Math.round(workQuality),reliability:Math.round(reliability),peerEvaluation:Math.round(peerScore),score:Math.round(score*10)/10});}const sum=result.reduce((a,x)=>a+x.score,0)||1;res.json(result.map(x=>({...x,contribution:Math.round(x.score/sum*1000)/10})));}catch(e){next(e)}});

app.get('/api/teams/:id/report',auth,async(req,res,next)=>{try{if(!await requireMember(req,res,req.params.id))return;const team=await one('SELECT * FROM teams WHERE id=?',[req.params.id]);const rows=await all(`SELECT m.user_id,u.name,m.role,m.position,COUNT(t.id) total,SUM(CASE WHEN t.status='verified' THEN 1 ELSE 0 END) verified FROM memberships m JOIN users u ON u.id=m.user_id LEFT JOIN tasks t ON t.team_id=m.team_id AND t.assignee_id=m.user_id WHERE m.team_id=? GROUP BY m.user_id,u.name,m.role,m.position ORDER BY u.name`,[req.params.id]);res.json({team,rows});}catch(e){next(e)}});


// Full UI state persistence for the agreed FairTeam interface. The UI keeps its rich
// interaction model client-side while this endpoint makes the workspace persistent
// per authenticated account in SQLite locally or PostgreSQL on Render.
app.get('/api/state',auth,async(req,res,next)=>{try{const row=await one('SELECT state FROM app_state WHERE user_id=?',[req.session.userId]);res.json({state:row?JSON.parse(row.state):null});}catch(e){next(e)}});
app.put('/api/state',auth,async(req,res,next)=>{try{const state=req.body?.state;if(!state||typeof state!=='object')return res.status(400).json({error:'Invalid state'});const raw=JSON.stringify(state);if(isPg){await pool.query('INSERT INTO app_state(user_id,state) VALUES($1,$2) ON CONFLICT(user_id) DO UPDATE SET state=$2,updated_at=NOW()',[req.session.userId,raw]);}else{await exec('INSERT INTO app_state(user_id,state) VALUES(?,?) ON CONFLICT(user_id) DO UPDATE SET state=?,updated_at=CURRENT_TIMESTAMP',[req.session.userId,raw,raw]);}res.json({ok:true});}catch(e){next(e)}});
app.get('/health',(req,res)=>res.json({ok:true,database:isPg?'postgresql':'sqlite'}));
app.use(express.static(path.join(__dirname,'public')));
app.get('*',(req,res)=>res.sendFile(path.join(__dirname,'public','index.html')));
app.use((err,req,res,next)=>{console.error(err);res.status(500).json({error:'Server error',detail:process.env.NODE_ENV==='production'?undefined:err.message});});

async function seedSampleAccount(){
  if(process.env.SAMPLE_MODE!=='true')return;
  let u=await one('SELECT * FROM users WHERE email=?',['sample@fairteam.local']);
  if(!u){const hash=await bcrypt.hash('123456',10);const r=await exec('INSERT INTO users(name,email,password) VALUES(?,?,?) RETURNING id',['Sample User','sample@fairteam.local',hash]);await exec('INSERT INTO settings(user_id) VALUES(?)',[r.lastInsertId]);u=await one('SELECT * FROM users WHERE id=?',[r.lastInsertId]);}
  let team=await one('SELECT id FROM teams WHERE created_by=? AND name=?',[u.id,'Sample Investment Team']);
  if(team)return;
  const r=await exec('INSERT INTO teams(name,description,period,created_by) VALUES(?,?,?,?) RETURNING id',['Sample Investment Team','A ready-to-explore FairTeam workspace with five members.','Sample period',u.id]);const tid=r.lastInsertId;
  await exec('INSERT INTO memberships(team_id,user_id,role,position) VALUES(?,?,?,?)',[tid,u.id,'leader','Project Lead']);
  const sample=[['Minh','Data Analyst'],['Linh','Researcher'],['An','Content Lead'],['Khoa','Designer']];const ids=[];
  for(const [name,pos] of sample){const email=`sample.${name.toLowerCase()}@fairteam.local`;let m=await one('SELECT * FROM users WHERE email=?',[email]);if(!m){const hash=await bcrypt.hash('sample123',10);const mr=await exec('INSERT INTO users(name,email,password) VALUES(?,?,?) RETURNING id',[name,email,hash]);await exec('INSERT INTO settings(user_id) VALUES(?)',[mr.lastInsertId]);m=await one('SELECT * FROM users WHERE id=?',[mr.lastInsertId]);}ids.push(m.id);await exec('INSERT INTO memberships(team_id,user_id,role,position) VALUES(?,?,?,?) ON CONFLICT(team_id,user_id) DO NOTHING',[tid,m.id,'member',pos]);}
  const tasks=[['Market research',ids[1],'verified',100],['Data cleaning',ids[0],'in_progress',65],['Project outline',ids[2],'todo',20],['Presentation design',ids[3],'in_progress',70],['Meeting notes',u.id,'todo',10]];
  for(const [title,assignee,status,progress] of tasks)await exec('INSERT INTO tasks(team_id,title,description,assignee_id,creator_id,priority,effort,status,progress) VALUES(?,?,?,?,?,?,?,?,?)',[tid,title,'Sample task for demonstrating the FairTeam workflow.',assignee,u.id,'Medium',3,status,progress]);
}

(async()=>{try{await initDb();await seedSampleAccount();let store;const opts={secret:process.env.SESSION_SECRET||'dev-only-change-this',resave:false,saveUninitialized:false,cookie:{httpOnly:true,sameSite:'lax',secure:process.env.NODE_ENV==='production',maxAge:1000*60*60*24*7}};if(isPg){const pgSession=require('connect-pg-simple')(session);store=new pgSession({pool,tableName:'user_sessions',createTableIfMissing:true});opts.store=store;}sessionMiddleware=session(opts);app.listen(PORT,'0.0.0.0',()=>console.log(`FairTeam running on http://localhost:${PORT} using ${isPg?'PostgreSQL':'SQLite'}`));}catch(e){console.error(e);process.exit(1)}})();
